//! Golden-frame parity tests: executes the shared scenario files from
//! tests/golden/screenbuffer/ and compares against the golden files
//! generated by tests/Wade.Tests/ScreenBufferGoldenTests.cs.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use wade::screen::{CellStyle, Color, ScreenBuffer};

/// Goldens are stored with LF endings but a CRLF checkout must not break
/// byte-for-byte comparison.
fn normalize_lf(s: &str) -> String {
    s.replace("\u{d}\u{a}", "\u{a}")
}

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/screenbuffer")
}

#[derive(Clone, Copy, PartialEq, Eq, Default)]
struct Style {
    fg: Option<Color>,
    bg: Option<Color>,
    bold: bool,
    dim: bool,
    inverse: bool,
    underline: bool,
    strikethrough: bool,
}

impl Style {
    /// Parses a FLAGS token: "-" for none, or a subset of "bdius".
    fn parse(token: &str) -> Self {
        let mut style = Self::default();
        if token.contains('b') {
            style.bold = true;
        }
        if token.contains('d') {
            style.dim = true;
        }
        if token.contains('i') {
            style.inverse = true;
        }
        if token.contains('u') {
            style.underline = true;
        }
        if token.contains('s') {
            style.strikethrough = true;
        }
        style
    }

    fn to_cell_style(self) -> CellStyle {
        CellStyle {
            fg: self.fg,
            bg: self.bg,
            bold: self.bold,
            dim: self.dim,
            inverse: self.inverse,
            underline: self.underline,
            strikethrough: self.strikethrough,
        }
    }
}

fn parse_color(token: &str) -> Option<Color> {
    let v: i32 = token.parse().expect("color component");
    if v < 0 { None } else { Some(Color { r: v as u8, g: 0, b: 0 }) }
}

fn parse_i32(token: &str) -> i32 {
    token.parse().expect("integer token")
}

fn parse_char(token: &str) -> char {
    if let Some(hex) = token.strip_prefix("\\u") {
        return char::from_u32(u32::from_str_radix(hex, 16).expect("hex char")).expect("valid char");
    }

    let mut chars = token.chars();
    let c = chars.next().expect("char token");
    assert!(chars.next().is_none(), "char token must be a single char: {token}");
    c
}

fn parse_style(tokens: &[&str]) -> Style {
    // tokens: FGR FGG FGB BGR BGG BGB FLAGS (put/fillrow) or FLAGS only (string op)
    if tokens.len() >= 7 {
        let fg = parse_color(tokens[0]).map(|c| {
            let g: i32 = tokens[1].parse().expect("fg green");
            let b: i32 = tokens[2].parse().expect("fg blue");
            Color { r: c.r, g: g as u8, b: b as u8 }
        });
        let bg = parse_color(tokens[3]).map(|c| {
            let g: i32 = tokens[4].parse().expect("bg green");
            let b: i32 = tokens[5].parse().expect("bg blue");
            Color { r: c.r, g: g as u8, b: b as u8 }
        });
        let mut style = Style::parse(tokens[6]);
        style.fg = fg;
        style.bg = bg;
        style
    } else {
        Style::parse(tokens[0])
    }
}

fn run_scenario(path: &Path) -> Vec<String> {
    let text = normalize_lf(&std::fs::read_to_string(path).expect("read scenario"));
    let mut buffer: Option<ScreenBuffer> = None;
    let mut out = String::new();
    let mut flushes = Vec::new();

    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let tokens: Vec<&str> = line.split_whitespace().collect();
        match tokens[0] {
            "resize" => match &mut buffer {
                Some(b) => b.resize(parse_i32(tokens[1]), parse_i32(tokens[2])),
                None => {
                    buffer = Some(ScreenBuffer::new(parse_i32(tokens[1]), parse_i32(tokens[2])));
                }
            },
            "put" => {
                buffer.as_mut().expect("resize before put").put(
                    parse_i32(tokens[1]),
                    parse_i32(tokens[2]),
                    parse_char(tokens[3]),
                    parse_style(&tokens[4..]).to_cell_style(),
                );
            }
            "string" => {
                // C# WriteString's default is int.MaxValue
                let max_width = if tokens.len() > 6 { parse_i32(tokens[6]) as i64 } else { i64::from(i32::MAX) };
                buffer.as_mut().expect("resize before string").write_string(
                    parse_i32(tokens[1]),
                    parse_i32(tokens[2]),
                    tokens[3],
                    parse_style(&tokens[4..5]).to_cell_style(),
                    max_width,
                );
            }
            "fillrow" => {
                buffer.as_mut().expect("resize before fillrow").fill_row(
                    parse_i32(tokens[1]),
                    parse_i32(tokens[2]),
                    parse_i32(tokens[3]),
                    parse_char(tokens[4]),
                    parse_style(&tokens[5..]).to_cell_style(),
                );
            }
            "clear" => buffer.as_mut().expect("resize before clear").clear(),
            "fullredraw" => buffer.as_mut().expect("resize before fullredraw").force_full_redraw(),
            "flush" => {
                let b = buffer.as_mut().expect("resize before flush");
                b.serialize(&mut out);
                flushes.push(out.clone());
            }
            other => panic!("Unknown op '{other}' in {}", path.display()),
        }
    }

    assert!(buffer.is_some(), "scenario {} has no resize op", path.display());
    flushes
}

fn format_golden(flushes: &[String]) -> String {
    let mut result = String::new();
    for (i, flush) in flushes.iter().enumerate() {
        let _ = writeln!(result, "=== flush {i} ===");
        let _ = writeln!(result, "{flush}");
    }
    result
}

#[test]
fn golden_frames_match_csharp_output() {
    let dir = golden_dir();
    let mut scenarios: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("golden dir")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "scn"))
        .collect();
    scenarios.sort();
    assert!(!scenarios.is_empty(), "no .scn scenarios found in {}", dir.display());

    let mut compared = 0;
    for scenario_path in scenarios {
        let golden_path = scenario_path.with_extension("golden.txt");
        let actual = format_golden(&run_scenario(&scenario_path));
        let expected = normalize_lf(&std::fs::read_to_string(&golden_path).unwrap_or_else(|_| {
            panic!("missing golden file {}; generate with the C# test and WADE_UPDATE_GOLDENS=1", golden_path.display())
        }));
        assert_eq!(expected, actual, "golden mismatch for {}", scenario_path.display());
        compared += 1;
    }

    assert!(compared >= 5, "expected at least 5 scenarios, compared {compared}");
}
