//! Input decode parity tests: executes the shared fixture files from
//! tests/golden/input/ and compares against the golden files generated by
//! tests/Wade.Tests/InputDecodeGoldenTests.cs. Runs on every platform: the
//! fixtures are synthetic data, no console required.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use wade::input::decode::{decode_records, RawRecord};
use wade::input::{InputEvent, MouseButton};

/// Goldens are stored with LF endings but a CRLF checkout must not break
/// byte-for-byte comparison.
fn normalize_lf(s: &str) -> String {
    s.replace("\u{d}\u{a}", "\u{a}")
}


fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/input")
}

fn parse_mods(token: &str) -> u32 {
    let mut state = 0;
    if token.contains('s') {
        state |= 0x0010; // ShiftPressed
    }
    if token.contains('a') {
        state |= 0x0002; // LeftAltPressed
    }
    if token.contains('c') {
        state |= 0x0008; // LeftCtrlPressed
    }
    state
}

fn parse_char(token: &str) -> u16 {
    match token {
        "-" => 0,
        t if t.starts_with("\\u") => u16::from_str_radix(&t[2..], 16).expect("hex char"),
        _ => {
            let mut chars = token.chars();
            let c = chars.next().expect("char token");
            assert!(chars.next().is_none(), "char token must be single: {token}");
            u16::try_from(u32::from(c)).expect("BMP char")
        }
    }
}

fn parse_i32(token: &str) -> i32 {
    token.parse().expect("integer token")
}

/// Parses a fixture into (records, window_width, window_height).
fn parse_fixture(path: &Path) -> (Vec<RawRecord>, i32, i32) {
    let text = normalize_lf(&std::fs::read_to_string(path).expect("read fixture"));
    let mut records = Vec::new();
    let mut window = (80, 25);

    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let tokens: Vec<&str> = line.split_whitespace().collect();
        match tokens[0] {
            "size" => window = (parse_i32(tokens[1]), parse_i32(tokens[2])),
            "kd" | "ku" => records.push(RawRecord::Key {
                key_down: tokens[0] == "kd",
                virtual_key_code: parse_i32(tokens[1]) as u16,
                unicode_char: parse_char(tokens[2]),
                control_key_state: parse_mods(tokens[3]),
            }),
            // mouse X Y BUTTONS CTRL FLAGS (CTRL is parsed for validation only;
            // the decoder ignores it, same as C#)
            "mouse" => {
                assert_eq!(tokens.len(), 6, "mouse record needs 5 fields: {line}");
                let _control_state = parse_i32(tokens[4]);
                records.push(RawRecord::Mouse {
                    x: parse_i32(tokens[1]) as i16,
                    y: parse_i32(tokens[2]) as i16,
                    button_state: parse_i32(tokens[3]) as u32,
                    event_flags: parse_i32(tokens[5]) as u32,
                });
            }
            "buf" => records.push(RawRecord::BufferSize),
            "other" => records.push(RawRecord::Other),
            other => panic!("Unknown record '{other}' in {}", path.display()),
        }
    }

    assert!(!records.is_empty(), "fixture {} has no records", path.display());
    (records, window.0, window.1)
}

fn format_char(ch: u16) -> String {
    match ch {
        0 => "-".to_string(),
        c if c < 0x20 => format!("\\u{c:04X}"),
        0x7F => "\\u007F".to_string(),
        _ => char::from_u32(u32::from(ch)).expect("valid char").to_string(),
    }
}

fn format_mods(shift: bool, alt: bool, control: bool) -> String {
    let mut mods = String::new();
    if shift {
        mods.push('s');
    }
    if alt {
        mods.push('a');
    }
    if control {
        mods.push('c');
    }
    if mods.is_empty() {
        mods.push('-');
    }
    mods
}

fn format_button(button: MouseButton) -> &'static str {
    match button {
        MouseButton::Left => "left",
        MouseButton::Right => "right",
        MouseButton::Middle => "middle",
        MouseButton::ScrollUp => "scrollup",
        MouseButton::ScrollDown => "scrolldown",
        MouseButton::None => "none",
    }
}

/// Formats decoded events in the same line format as the C# harness
/// (`FormatEvents` in tests/Wade.Tests/InputDecodeGoldenTests.cs).
fn format_events(events: &[InputEvent]) -> String {
    let mut result = String::new();
    for evt in events {
        match evt {
            InputEvent::Key(k) => {
                let _ = writeln!(
                    result,
                    "key {} {} {}",
                    k.key.vk(),
                    format_char(k.key_char),
                    format_mods(k.shift, k.alt, k.control)
                );
            }
            InputEvent::Paste(text) => {
                let _ = writeln!(result, "paste {text}");
            }
            InputEvent::Mouse(m) => {
                let _ = writeln!(
                    result,
                    "mouse {} {} {} {}",
                    format_button(m.button),
                    m.row,
                    m.col,
                    if m.is_release { "release" } else { "press" }
                );
            }
            InputEvent::Resize(r) => {
                let _ = writeln!(result, "resize {} {}", r.width, r.height);
            }
            // Only produced by loader threads, never by console decoding
            InputEvent::GitStatusReady(_) => {}
            InputEvent::GitActionComplete(_) => {}
            InputEvent::FileOperationComplete(_) => {}
            InputEvent::FileOperationProgress(_) => {}
            InputEvent::DirectorySizeReady(_) => {}
            InputEvent::InlineDirSizeReady(_) => {}
            InputEvent::InlineDirSizeComplete(_) => {}
            InputEvent::FileSystemChanged(_) => {}
        }
    }
    result
}

#[test]
fn input_decode_fixtures_match_csharp_output() {
    let dir = golden_dir();
    let mut fixtures: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("golden dir")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "scn"))
        .collect();
    fixtures.sort();
    assert!(
        !fixtures.is_empty(),
        "no .scn fixtures found in {}",
        dir.display()
    );

    let mut compared = 0;
    for fixture_path in fixtures {
        let golden_path = fixture_path.with_extension("golden.txt");
        let expected = normalize_lf(&std::fs::read_to_string(&golden_path).unwrap_or_else(|_| {
            panic!(
                "missing golden file {}; generate with the C# test and WADE_UPDATE_GOLDENS=1",
                golden_path.display()
            )
        }));

        let (records, window_width, window_height) = parse_fixture(&fixture_path);
        let events = decode_records(&records, window_width, window_height);
        let actual = format_events(&events);

        assert_eq!(
            expected, actual,
            "golden mismatch for {}",
            fixture_path.display()
        );
        compared += 1;
    }

    assert!(
        compared >= 5,
        "expected at least 5 fixtures, compared {compared}"
    );
}
