//! Renderer golden-frame parity tests: executes the shared fixture files
//! from tests/golden/renderer/ and compares against the golden files
//! generated by tests/Wade.Tests/PaneRendererGoldenTests.cs.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use wade::app::dialogs;
use wade::app::input_reader::AppAction;
use wade::fs::directory_contents::{FileSystemEntry, GitFileStatus, SortMode, DRIVES_PATH};
use wade::screen::{CellStyle, Color, ScreenBuffer};
use wade::preview::{MetadataEntry, MetadataSection};
use wade::ui::action_palette::{ActionMenuItem, ActionMenuLevel};
use wade::ui::format_helpers::DateParts;
use wade::ui::help_overlay;
use wade::ui::layout::{Layout, Rect};
use wade::ui::notification::{Notification, NotificationKind};
use wade::ui::pane_renderer::PaneRenderer;
use wade::ui::status_bar;
use wade::ui::text_input::TextInput;

/// Goldens are stored with LF endings but a CRLF checkout must not break
/// byte-for-byte comparison.
fn normalize_lf(s: &str) -> String {
    s.replace("\u{d}\u{a}", "\u{a}")
}


fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/renderer")
}

fn parse_i32(token: &str) -> i32 {
    token.parse().expect("integer token")
}

fn parse_i64(token: &str) -> i64 {
    token.parse().expect("long token")
}

fn parse_date(token: &str) -> DateParts {
    // yyyy-MM-ddTHH:mm:ss
    let bytes = token.as_bytes();
    assert_eq!(token.len(), 19, "date format: {token}");
    let num = |a: usize, b: usize| -> i32 {
        token[a..b].parse().expect("date component")
    };
    let _ = bytes;
    assert_eq!(&token[4..5], "-");
    assert_eq!(&token[7..8], "-");
    assert_eq!(&token[10..11], "T");
    assert_eq!(&token[13..14], ":");
    assert_eq!(&token[16..17], ":");
    DateParts {
        year: num(0, 4),
        month: num(5, 7) as u32,
        day: num(8, 10) as u32,
        hour: num(11, 13) as u32,
        minute: num(14, 16) as u32,
    }
}

fn unquote(s: &str) -> String {
    s.trim_matches('"').to_string()
}

/// All `"..."` spans in the string, in order.
fn quoted_spans(s: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"'
            && let Some(end) = s[i + 1..].find('"')
        {
            out.push(s[i + 1..i + 1 + end].to_string());
            i += end + 2;
        } else {
            i += 1;
        }
    }
    out
}

/// Finder fixtures root their entries at a real absolute path so the
/// relative-path display matches across OSes (names carry no separators).
fn finder_base_path() -> &'static str {
    if cfg!(windows) { "C:\\fixture" } else { "/fixture" }
}

fn make_entry(name: &str, is_directory: bool, size: i64, modified: DateParts) -> FileSystemEntry {
    FileSystemEntry {
        name: name.to_string(),
        full_path: format!("C:\\fixture\\{name}"),
        is_directory,
        size,
        last_modified: modified,
        link_target: None,
        is_broken_symlink: false,
        is_drive: false,
        is_cloud_placeholder: false,
        is_junction_point: false,
        is_app_exec_link: false,
        app_exec_link_target: None,
        drive_media_type: wade::fs::DriveMediaType::Unknown,
        drive_format: None,
        drive_label: None,
        drive_free_space: 0,
        drive_total_size: 0,
    }
}

fn make_drive_entry(name: &str, format: &str, label: &str, free: i64, total: i64) -> FileSystemEntry {
    FileSystemEntry {
        name: name.to_string(),
        full_path: format!("{name}\\"),
        is_directory: true,
        size: 0,
        last_modified: DateParts::default(),
        link_target: None,
        is_broken_symlink: false,
        is_drive: true,
        is_cloud_placeholder: false,
        is_junction_point: false,
        is_app_exec_link: false,
        app_exec_link_target: None,
        drive_media_type: wade::fs::DriveMediaType::Unknown,
        drive_format: Some(format.to_string()),
        drive_label: Some(label.to_string()),
        drive_free_space: free,
        drive_total_size: total,
    }
}

fn pane_rect(layout: &Layout, pane: &str) -> Rect {
    match pane {
        "left" => layout.left_pane,
        "right" => layout.right_pane,
        "expanded" => layout.expanded_pane,
        _ => layout.center_pane,
    }
}

/// Port of RendererFixtureRunner.LoadPreviewLines: highlighted text (as
/// TextPreviewProvider) or the hex dump of a tests/golden/preview/files file.
fn load_preview_lines(scenario_path: &Path, kind: &str, file_name: &str) -> Vec<wade::highlight::StyledLine> {
    let path = scenario_path
        .parent()
        .expect("scenario dir")
        .join("..")
        .join("preview")
        .join("files")
        .join(file_name);
    let path = path.to_string_lossy();

    if kind == "hex" {
        return wade::fs::hex_preview::get_preview_lines(&path, &wade::input::CancelToken::new()).expect("hex lines");
    }

    let (lines, _) = wade::fs::file_preview::get_preview_lines(&path);
    let lines: Vec<&str> = lines.iter().map(String::as_str).collect();
    wade::highlight::highlight(&lines, &path)
}

fn run_scenario(path: &Path) -> String {
    let text = normalize_lf(&std::fs::read_to_string(path).expect("read fixture"));
    let mut width = 80;
    let mut height = 25;
    let mut buffer: Option<ScreenBuffer> = None;
    let mut layout = Layout::default();
    let mut lists: HashMap<String, Vec<FileSystemEntry>> = HashMap::new();
    let mut current_list: Option<String> = None;
    let mut palette_title = String::new();
    let mut palette_depth = 1;
    let mut palette_selected = 0;
    let mut palette_items: Option<Vec<ActionMenuItem>> = None;
    let mut notification: Option<Notification> = None;
    let mut config_state: Option<wade::ui::config_dialog::ConfigDialogState> = None;
    let mut bookmark_store: Option<wade::fs::bookmark_store::BookmarkStore> = None;
    let mut bookmark_input: Option<TextInput> = None;
    let mut bookmark_selected: usize = 0;
    let mut bookmark_scroll: usize = 0;
    let mut ctx_items: Option<Vec<ActionMenuItem>> = None;
    let mut ctx_anchor: (i32, i32) = (0, 0);
    let mut branch_name = String::new();
    let mut ahead_behind_text = String::new();
    let mut git_statuses: Option<std::collections::HashMap<String, GitFileStatus>> = None;
    let mut current_git_statuses: std::collections::HashMap<String, GitFileStatus> = std::collections::HashMap::new();
    let mut repo_root: Option<String> = None;
    let mut flushes: Vec<String> = Vec::new();
    let mut out = String::new();
    let mut finder_query = String::new();
    let mut finder_args: Vec<usize> = Vec::new();
    let mut finder_state = String::new();
    let mut finder_entries: Option<Vec<(FileSystemEntry, Vec<usize>)>> = None;
    let mut metadata_sections: Vec<MetadataSection> = Vec::new();

    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some(rest) = line.strip_prefix("platform ") {
            // platform windows: skip the whole scenario on other OSes
            // (scenarios that render platform-dependent content)
            if rest.trim() == "windows" && !cfg!(windows) {
                return "PLATFORM-SKIPPED".to_string();
            }

            continue;
        }

        let tokens: Vec<&str> = line.split_whitespace().collect();
        match tokens[0] {
            "size" => {
                width = parse_i32(tokens[1]);
                height = parse_i32(tokens[2]);
                buffer = Some(ScreenBuffer::new(width, height));
            }
            "list" => {
                lists.insert(tokens[1].to_string(), Vec::new());
                current_list = Some(tokens[1].to_string());
            }
            "dir" => {
                let modified = if tokens.len() > 2 { parse_date(tokens[2]) } else { DateParts::default() };
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_entry(tokens[1], true, 0, modified));
            }
            "file" => {
                let size = parse_i64(tokens[2]);
                let modified = if tokens.len() > 3 { parse_date(tokens[3]) } else { DateParts::default() };
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_entry(tokens[1], false, size, modified));
            }
            "drive" => {
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_drive_entry(tokens[1], tokens[2], &unquote(tokens[3]), parse_i64(tokens[4]), parse_i64(tokens[5])));
            }
            "endlist" => current_list = None,
            "layout" => {
                layout.calculate(
                    width,
                    height,
                    matches!(tokens[1], "3pane" | "preview"),
                    matches!(tokens[1], "3pane" | "parent"),
                );
            }
            "headers" => {
                let flags: Vec<&str> = tokens[2..].to_vec();
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_column_headers(
                    buffer,
                    pane_rect(&layout, tokens[1]),
                    flags.contains(&"icons"),
                    flags.contains(&"size"),
                    flags.contains(&"date"),
                    flags.contains(&"drive"),
                    flags.contains(&"status"),
                );
            }
            "filelist" => {
                let pane = tokens[1];
                let list_name = tokens[2];
                let selected = parse_i32(tokens[3]);
                let scroll = parse_i32(tokens[4]);
                let active = tokens[5] == "active";
                let flags: Vec<&str> = tokens[6..].to_vec();
                let entries = &lists[list_name];
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_file_list(
                    buffer,
                    pane_rect(&layout, pane),
                    entries,
                    selected,
                    scroll,
                    active,
                    flags.contains(&"icons"),
                    flags.contains(&"size"),
                    flags.contains(&"date"),
                    &std::collections::HashSet::new(),
                    git_statuses.as_ref(),
                    None,
                    flags.contains(&"drive"),
                );
            }
            "message" => {
                let pane = tokens[1];
                let msg = unquote(line.splitn(3, ' ').nth(2).expect("message text"));
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_message(buffer, pane_rect(&layout, pane), &msg);
            }
            "notify" => {
                let msg = unquote(line.splitn(3, ' ').nth(2).expect("notification text"));
                notification = Some(Notification {
                    message: msg,
                    kind: match tokens[1] {
                        "success" => NotificationKind::Success,
                        "error" => NotificationKind::Error,
                        _ => NotificationKind::Info,
                    },
                    timestamp_ms: 0,
                });
            }
            "statusbar" => {
                // statusbar PATH SELECTED ITEM_COUNT [list LISTNAME] [branch "NAME"] [aheadbehind "TEXT"]
                let path = unquote(tokens[1]);
                let selected = parse_i32(tokens[2]) as usize;
                let item_count = parse_i32(tokens[3]) as usize;
                let selected_entry = if tokens.contains(&"list") {
                    let list_idx = tokens.iter().position(|t| *t == "list").expect("list keyword");
                    lists[tokens[list_idx + 1]].get(selected)
                } else {
                    None
                };

                let branch_name_inline = extract_quoted_arg(line, "branch ");
                let ahead_behind_inline = extract_quoted_arg(line, "aheadbehind ");
                let branch_arg = if branch_name_inline.is_empty() { None } else { Some(branch_name_inline.as_str()) };
                let ahead_behind_arg = if ahead_behind_inline.is_empty() { None } else { Some(ahead_behind_inline.as_str()) };

                let buffer = buffer.as_mut().expect("size op first");
                status_bar::render(
                    buffer,
                    layout.status_bar,
                    &path,
                    item_count,
                    selected,
                    selected_entry,
                    None,
                    None,
                    None,
                    notification.take(),
                    0,
                    SortMode::Name,
                    true,
                    0,
                    false,
                    branch_arg,
                    ahead_behind_arg,
                );
                branch_name.clear();
                ahead_behind_text.clear();
                let _ = branch_name_inline;
            }
            "help" => {
                let buffer = buffer.as_mut().expect("size op first");
                help_overlay::render(buffer, width, height);
            }
            "confirmdlg" => {
                // confirmdlg "TITLE" "MESSAGE" (\n in MESSAGE is a line break)
                let args = quoted_spans(line);
                let title = args[0].clone();
                let message = args[1].replace("\\n", "\n");
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_confirm_dialog(
                    buffer,
                    width,
                    height,
                    if title == "-" { None } else { Some(&title) },
                    &message,
                );
            }
            "textinputdlg" => {
                // textinputdlg "TITLE" "VALUE"
                let args = quoted_spans(line);
                let title = args[0].clone();
                let value = args[1].clone();
                let mut input = TextInput::new(&value);
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_text_input_dialog(
                    buffer,
                    width,
                    height,
                    if title == "-" { None } else { Some(&title) },
                    Some(&mut input),
                );
            }
            "gotopathdlg" => {
                // gotopathdlg "VALUE" ["SUGGESTION"]
                let rest = line["gotopathdlg ".len()..].to_string();
                let spans = quoted_spans(&rest);
                let value = unquote(&spans[0]);
                let mut input = TextInput::new(&value);
                let suggestion = if spans.len() > 1 { Some(unquote(&spans[1])) } else { None };
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_go_to_path_dialog(buffer, width, height, Some(&mut input), suggestion.as_deref());
            }
            "palette" => {
                // palette "TITLE" DEPTH SELECTED
                let rest = &line["palette ".len()..];
                let spans = quoted_spans(rest);
                palette_title = spans[0].clone();
                let after_title = &rest[rest[1..].find('"').expect("closing quote") + 2..];
                let nums: Vec<&str> = after_title.split_whitespace().collect();
                palette_depth = parse_i32(nums[0]);
                palette_selected = parse_i32(nums[1]);
                palette_items = Some(Vec::new());
            }
            "pitem" => {
                // pitem "Label" "Shortcut" [sub]
                let spans = quoted_spans(&line["pitem ".len()..]);
                palette_items
                    .as_mut()
                    .expect("palette op first")
                    .push(ActionMenuItem::new(&spans[0], &spans[1], AppAction::None));
            }
            "endpalette" => {
                let items = palette_items.take().expect("palette op first");
                let mut level = ActionMenuLevel::new(&palette_title, items);
                level.selected_index = palette_selected.max(0) as usize;
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_action_palette(buffer, width, height, &mut level, palette_depth);
            }
            "searchbar" => {
                // searchbar ACTIVE "FILTER"
                let active = tokens[1] == "active";
                let filter = unquote(line.splitn(3, ' ').nth(2).expect("filter"));
                let mut input = TextInput::new(&filter);
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_search_bar(
                    buffer,
                    layout.center_pane,
                    active,
                    &filter,
                    if active { Some(&mut input) } else { None },
                );
            }
            "textinput" => {
                // textinput ROW COL WIDTH "VALUE"
                let row = parse_i32(tokens[1]);
                let col = parse_i32(tokens[2]);
                let w = parse_i32(tokens[3]);
                let value = unquote(line.splitn(5, ' ').nth(4).expect("value"));
                let mut input = TextInput::new(&value);
                let style = CellStyle {
                    fg: Some(Color { r: 200, g: 200, b: 200 }),
                    bg: None,
                    ..CellStyle::default()
                };
                let buffer = buffer.as_mut().expect("size op first");
                input.render(buffer, row, col, w, style);
            }
            "repo" => {
                // repo "PATH" | repo off: the simulated repo root for the
                // git menu builders
                let value = unquote(line.split_once(' ').map(|x| x.1).expect("repo path"));
                repo_root = if value == "off" { None } else { Some(value) };
            }
            "gitappend" => {
                // gitappend "SELECTEDPATH"|- : append the palette git block
                let rest = line["gitappend ".len()..].trim();
                let selected_path = if rest == "-" { None } else { Some(unquote(rest)) };
                let ctx = wade::app::git_menu_items::GitMenuContext {
                    repo_root: repo_root.as_deref(),
                    statuses: git_statuses.as_ref(),
                    selected_path: selected_path.as_deref(),
                    marked_paths: &std::collections::HashSet::new(),
                };
                palette_items
                    .as_mut()
                    .expect("palette op first")
                    .extend(wade::app::git_menu_items::build_git_menu_items(&ctx));
            }
            "ctxgitappend" => {
                // ctxgitappend "SELECTEDPATH"|- : append the context menu git block
                let rest = line["ctxgitappend ".len()..].trim();
                let selected_path = if rest == "-" { None } else { Some(unquote(rest)) };
                let ctx = wade::app::git_menu_items::GitMenuContext {
                    repo_root: repo_root.as_deref(),
                    statuses: git_statuses.as_ref(),
                    selected_path: selected_path.as_deref(),
                    marked_paths: &std::collections::HashSet::new(),
                };
                ctx_items
                    .as_mut()
                    .expect("ctxmenu op first")
                    .extend(wade::app::git_menu_items::build_git_context_menu_items(&ctx));
            }
            "gitstatuses" => {
                // gitstatuses followed by gs "FULLPATH" CODE lines and
                // endgitstatuses; CODE is untracked/modified/staged/
                // ignored/conflict or +-joined (e.g. staged+modified)
                current_git_statuses = std::collections::HashMap::new();
            }
            "gs" => {
                // gs "FULLPATH" CODE[+CODE...]
                let rest = line["gs ".len()..].to_string();
                let path = unquote(quoted_spans(rest.trim())[0].as_str());
                let after = &rest[rest[1..].find('"').expect("closing quote") + 2..];
                let status_text = after.trim();
                let mut status = GitFileStatus::NONE;
                for part in status_text.split('+').filter(|p| !p.is_empty()) {
                    status |= match part.trim() {
                        "untracked" => GitFileStatus::UNTRACKED,
                        "modified" => GitFileStatus::MODIFIED,
                        "staged" => GitFileStatus::STAGED,
                        "ignored" => GitFileStatus::IGNORED,
                        "conflict" => GitFileStatus::CONFLICT,
                        other => panic!("unknown git status code '{other}'"),
                    };
                }

                current_git_statuses.insert(path, status);
            }
            "endgitstatuses" => {
                git_statuses = Some(std::mem::take(&mut current_git_statuses));
            }
            "gsoff" => {
                git_statuses = None;
            }
            "branch" => {
                branch_name = extract_quoted_arg(line, "branch ");
            }
            "aheadbehind" => {
                ahead_behind_text = extract_quoted_arg(line, "aheadbehind ");
            }
            "finder" => {
                // finder "QUERY" SELECTED SCROLL MATCHING TOTAL scanning|done|none
                finder_query = quoted_spans(line)[0].clone();
                let rest: Vec<&str> = line[line.rfind('"').unwrap() + 1..].split_whitespace().collect();
                finder_args = rest[..4].iter().map(|t| t.parse().expect("finder number")).collect();
                finder_state = rest[4].to_string();
                finder_entries = Some(Vec::new());
            }
            "fentry" => {
                // fentry NAME dir|file POSITIONS (comma-separated, or -)
                let positions: Vec<usize> = if tokens[3] == "-" {
                    Vec::new()
                } else {
                    tokens[3].split(',').map(|t| t.parse().expect("position")).collect()
                };
                let mut entry = make_entry(tokens[1], tokens[2] == "dir", 0, DateParts::default());
                entry.full_path = Path::new(finder_base_path()).join(tokens[1]).to_string_lossy().into_owned();
                finder_entries.as_mut().expect("finder first").push((entry, positions));
            }
            "endfinder" => {
                let entries = finder_entries.take().expect("finder first");
                let scroll = finder_args[1];
                let items: Vec<wade::app::file_finder::FinderItem<'_>> = entries
                    .iter()
                    .skip(scroll)
                    .map(|(entry, positions)| wade::app::file_finder::FinderItem {
                        entry,
                        match_positions: positions,
                    })
                    .collect();
                let view = wade::app::file_finder::FinderView {
                    scanning: finder_state == "scanning",
                    has_entries: finder_state != "none",
                    display_count: entries.len(),
                    matching: finder_args[2],
                    total: finder_args[3],
                    current_path: finder_base_path(),
                    selected_index: finder_args[0],
                    scroll_offset: scroll,
                    items: &items,
                };
                let buffer = buffer.as_mut().expect("size op first");
                wade::app::file_finder::render_file_finder_view(
                    buffer,
                    width,
                    height,
                    &view,
                    &mut TextInput::new(&finder_query),
                );
            }
            "preview" => {
                // preview PANE text|hex FILE SCROLL lines|nolines
                let lines = load_preview_lines(path, tokens[2], tokens[3]);
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_preview(
                    buffer,
                    pane_rect(&layout, tokens[1]),
                    &lines,
                    tokens[4].parse().expect("scroll"),
                    tokens[5] == "lines",
                );
            }
            "msection" => {
                // msection "HEADER" | msection - (no header)
                let header = (tokens[1] != "-").then(|| quoted_spans(line)[0].clone());
                metadata_sections.push(MetadataSection { header, entries: Vec::new() });
            }
            "mentry" => {
                // mentry "LABEL" "VALUE"
                let args = quoted_spans(line);
                metadata_sections
                    .last_mut()
                    .expect("msection first")
                    .entries
                    .push(MetadataEntry::new(&args[0], &args[1]));
            }
            "metadata" => {
                // metadata PANE: metadata-only right pane
                let pane = pane_rect(&layout, tokens[1]);
                let lines = wade::ui::metadata_renderer::render(&metadata_sections, pane.width);
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_preview(buffer, pane, &lines, 0, false);
            }
            "metatext" => {
                // metatext PANE text|hex FILE: metadata header above the preview
                let lines = load_preview_lines(path, tokens[2], tokens[3]);
                let buffer = buffer.as_mut().expect("size op first");
                wade::app::preview::render_metadata_with_text(
                    buffer,
                    pane_rect(&layout, tokens[1]),
                    &metadata_sections,
                    &lines,
                    tokens[2] == "hex",
                );
            }
            "metaimage" => {
                // metaimage PANE: metadata header above a blank image area
                let buffer = buffer.as_mut().expect("size op first");
                let top = wade::app::preview::render_metadata_with_image(buffer, pane_rect(&layout, tokens[1]), &metadata_sections);
                buffer.write_string(0, 0, &format!("top={top}"), CellStyle::default(), 20);
            }
            "combined" => {
                // combined PANE text|hex FILE: preview text above a blank image area
                let lines = load_preview_lines(path, tokens[2], tokens[3]);
                let buffer = buffer.as_mut().expect("size op first");
                let top =
                    wade::app::preview::render_combined_preview(buffer, pane_rect(&layout, tokens[1]), &lines, tokens[2] == "hex");
                buffer.write_string(0, 0, &format!("top={top}"), CellStyle::default(), 20);
            }
            "flush" => {
                let buffer = buffer.as_mut().expect("size op first");
                buffer.serialize(&mut out);
                flushes.push(out.clone());
            }
            "configdlg" => {
                config_state = Some(wade::ui::config_dialog::ConfigDialogState::from_app_config(&wade::app::AppConfig::default()));
            }
            "csel" => {
                config_state.as_mut().expect("configdlg op first").selected_index = parse_i32(tokens[1]).max(0) as usize;
            }
            "ctoggle" => {
                config_state.as_mut().expect("configdlg op first").toggle_selected();
            }
            "ccycle" => {
                let state = config_state.as_mut().expect("configdlg op first");
                if tokens[1] == "next" {
                    state.cycle_next_selected();
                } else {
                    state.cycle_prev_selected();
                }
            }
            "cnav" => {
                let state = config_state.as_mut().expect("configdlg op first");
                match tokens[1] {
                    "up" => state.move_up(),
                    "down" => state.move_down(),
                    "left" => state.cycle_prev_selected(),
                    _ => state.cycle_next_selected(),
                }
            }
            "configrender" => {
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_config_dialog(buffer, width, height, config_state.as_ref().expect("configdlg op first"));
            }
            "bmark" => {
                let store = bookmark_store.get_or_insert_with(|| {
                    wade::fs::bookmark_store::BookmarkStore::new(Some(
                        std::env::temp_dir().join(format!("wade-fixture-bookmarks-{}", std::process::id())),
                    ))
                });
                store.add(&unquote(line.split_once(' ').map(|x| x.1).expect("path")));
            }
            "bfilter" => {
                let mut input = TextInput::default();
                let value = unquote(line.split_once(' ').map(|x| x.1).expect("text"));
                for ch in value.chars() {
                    input.insert_char(ch);
                }
                bookmark_input = Some(input);
            }
            "bsel" => {
                bookmark_selected = parse_i32(tokens[1]).max(0) as usize;
            }
            "bscroll" => {
                bookmark_scroll = parse_i32(tokens[1]).max(0) as usize;
            }
            "bookmarkrender" => {
                let store = bookmark_store.as_ref().expect("bmark op first");
                let filter = bookmark_input.as_ref().map_or(String::new(), |input| input.value().to_string());
                let filtered: Vec<String> = store
                    .bookmarks()
                    .iter()
                    .filter(|bookmark| filter.is_empty() || bookmark.to_ascii_lowercase().contains(&filter.to_ascii_lowercase()))
                    .cloned()
                    .collect();
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_bookmarks(buffer, width, height, &filtered, bookmark_selected, bookmark_scroll, bookmark_input.as_mut());
            }
            "ctxmenu" => {
                // ctxmenu ANCHORROW ANCHORCOL
                ctx_anchor = (parse_i32(tokens[1]), parse_i32(tokens[2]));
                ctx_items = Some(Vec::new());
            }
            "citem" => {
                let spans = quoted_spans(&line["citem ".len()..]);
                ctx_items
                    .as_mut()
                    .expect("ctxmenu op first")
                    .push(ActionMenuItem::new(&spans[0], &spans[1], AppAction::None));
            }
            "endctxmenu" => {
                let items = ctx_items.take().expect("ctxmenu op first");
                let state = wade::ui::context_menu::ContextMenuState::new(items, ctx_anchor.0, ctx_anchor.1);
                let buffer = buffer.as_mut().expect("size op first");
                wade::ui::context_menu::render(buffer, width, height, &state);
            }
            other => panic!("Unknown op '{other}' in {}", path.display()),
        }
    }

    assert!(buffer.is_some(), "scenario {} has no size op", path.display());

    let mut golden = String::new();
    for (i, flush) in flushes.iter().enumerate() {
        let _ = writeln!(golden, "=== flush {i} ===");
        let _ = writeln!(golden, "{flush}");
    }
    golden
}

const MIN_FIXTURES: usize = 5;

#[test]
fn renderer_fixtures_match_csharp_output() {
    let dir = golden_dir();
    let mut fixtures: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("golden dir")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "scn"))
        .collect();
    fixtures.sort();
    assert!(
        fixtures.len() >= MIN_FIXTURES,
        "no .scn fixtures found in {}",
        dir.display()
    );

    let mut compared = 0;
    for fixture_path in fixtures {
        let golden_path = fixture_path.with_extension("golden.txt");
        let expected = normalize_lf(&std::fs::read_to_string(&golden_path).unwrap_or_else(|_| {
            panic!(
                "missing golden file {}; generate with the C# test and WADE_UPDATE_GOLDENS=1",
                golden_path.display()
            )
        }));

        let actual = run_scenario(&fixture_path);
        if actual == "PLATFORM-SKIPPED" {
            continue;
        }

        assert_eq!(
            expected, actual,
            "golden mismatch for {}",
            fixture_path.display()
        );
        compared += 1;
    }

    assert!(
        compared >= MIN_FIXTURES,
        "expected at least {MIN_FIXTURES} fixtures, compared {compared}"
    );
}

// Suppress unused warnings for ported constants only reachable via fixtures.
#[test]
fn drives_path_constant_matches_csharp() {
    assert_eq!(DRIVES_PATH, "::drives");
}

#[allow(dead_code)] // fixture helper, mirrors RendererFixtureRunner.ExtractQuotedArg
fn extract_quoted_arg(line: &str, keyword: &str) -> String {
    let Some(idx) = line.find(keyword) else {
        return String::new();
    };

    let rest = &line[idx + keyword.len()..];
    let trimmed = rest.trim();
    if let Some(stripped) = trimmed.strip_prefix('"')
        && let Some(end) = stripped.find('"')
    {
        return stripped[..end].to_string();
    }

    trimmed.to_string()
}
