//! Renderer golden-frame parity tests: executes the shared fixture files
//! from tests/golden/renderer/ and compares against the golden files
//! generated by tests/Wade.Tests/PaneRendererGoldenTests.cs.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use wade::app::dialogs;
use wade::app::input_reader::AppAction;
use wade::fs::directory_contents::{FileSystemEntry, SortMode, DRIVES_PATH};
use wade::screen::{CellStyle, Color, ScreenBuffer};
use wade::ui::action_palette::{ActionMenuItem, ActionMenuLevel};
use wade::ui::format_helpers::DateParts;
use wade::ui::help_overlay;
use wade::ui::layout::{Layout, Rect};
use wade::ui::notification::{Notification, NotificationKind};
use wade::ui::pane_renderer::PaneRenderer;
use wade::ui::status_bar;
use wade::ui::text_input::TextInput;

/// Goldens are stored with LF endings but a CRLF checkout must not break
/// byte-for-byte comparison.
fn normalize_lf(s: &str) -> String {
    s.replace("\u{d}\u{a}", "\u{a}")
}


fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/renderer")
}

fn parse_i32(token: &str) -> i32 {
    token.parse().expect("integer token")
}

fn parse_i64(token: &str) -> i64 {
    token.parse().expect("long token")
}

fn parse_date(token: &str) -> DateParts {
    // yyyy-MM-ddTHH:mm:ss
    let bytes = token.as_bytes();
    assert_eq!(token.len(), 19, "date format: {token}");
    let num = |a: usize, b: usize| -> i32 {
        token[a..b].parse().expect("date component")
    };
    let _ = bytes;
    assert_eq!(&token[4..5], "-");
    assert_eq!(&token[7..8], "-");
    assert_eq!(&token[10..11], "T");
    assert_eq!(&token[13..14], ":");
    assert_eq!(&token[16..17], ":");
    DateParts {
        year: num(0, 4),
        month: num(5, 7) as u32,
        day: num(8, 10) as u32,
        hour: num(11, 13) as u32,
        minute: num(14, 16) as u32,
    }
}

fn unquote(s: &str) -> String {
    s.trim_matches('"').to_string()
}

/// All `"..."` spans in the string, in order.
fn quoted_spans(s: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"'
            && let Some(end) = s[i + 1..].find('"')
        {
            out.push(s[i + 1..i + 1 + end].to_string());
            i += end + 2;
        } else {
            i += 1;
        }
    }
    out
}

fn make_entry(name: &str, is_directory: bool, size: i64, modified: DateParts) -> FileSystemEntry {
    FileSystemEntry {
        name: name.to_string(),
        full_path: format!("C:/fixture/{name}"),
        is_directory,
        size,
        last_modified: modified,
        link_target: None,
        is_broken_symlink: false,
        is_drive: false,
        is_cloud_placeholder: false,
        is_junction_point: false,
        is_app_exec_link: false,
        app_exec_link_target: None,
        drive_format: None,
        drive_label: None,
        drive_free_space: 0,
        drive_total_size: 0,
    }
}

fn make_drive_entry(name: &str, format: &str, label: &str, free: i64, total: i64) -> FileSystemEntry {
    FileSystemEntry {
        name: name.to_string(),
        full_path: format!("{name}\\"),
        is_directory: true,
        size: 0,
        last_modified: DateParts::default(),
        link_target: None,
        is_broken_symlink: false,
        is_drive: true,
        is_cloud_placeholder: false,
        is_junction_point: false,
        is_app_exec_link: false,
        app_exec_link_target: None,
        drive_format: Some(format.to_string()),
        drive_label: Some(label.to_string()),
        drive_free_space: free,
        drive_total_size: total,
    }
}

fn pane_rect(layout: &Layout, pane: &str) -> Rect {
    match pane {
        "left" => layout.left_pane,
        "right" => layout.right_pane,
        _ => layout.center_pane,
    }
}

fn run_scenario(path: &Path) -> String {
    let text = normalize_lf(&std::fs::read_to_string(path).expect("read fixture"));
    let mut width = 80;
    let mut height = 25;
    let mut buffer: Option<ScreenBuffer> = None;
    let mut layout = Layout::default();
    let mut lists: HashMap<String, Vec<FileSystemEntry>> = HashMap::new();
    let mut current_list: Option<String> = None;
    let mut palette_title = String::new();
    let mut palette_depth = 1;
    let mut palette_selected = 0;
    let mut palette_items: Option<Vec<ActionMenuItem>> = None;
    let mut notification: Option<Notification> = None;
    let mut config_state: Option<wade::ui::config_dialog::ConfigDialogState> = None;
    let mut bookmark_store: Option<wade::fs::bookmark_store::BookmarkStore> = None;
    let mut bookmark_input: Option<TextInput> = None;
    let mut bookmark_selected: usize = 0;
    let mut bookmark_scroll: usize = 0;
    let mut ctx_items: Option<Vec<ActionMenuItem>> = None;
    let mut ctx_anchor: (i32, i32) = (0, 0);
    let mut flushes: Vec<String> = Vec::new();
    let mut out = String::new();

    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some(rest) = line.strip_prefix("platform ") {
            // platform windows: skip the whole scenario on other OSes
            // (scenarios that render platform-dependent content)
            if rest.trim() == "windows" && !cfg!(windows) {
                return "PLATFORM-SKIPPED".to_string();
            }

            continue;
        }

        let tokens: Vec<&str> = line.split_whitespace().collect();
        match tokens[0] {
            "size" => {
                width = parse_i32(tokens[1]);
                height = parse_i32(tokens[2]);
                buffer = Some(ScreenBuffer::new(width, height));
            }
            "list" => {
                lists.insert(tokens[1].to_string(), Vec::new());
                current_list = Some(tokens[1].to_string());
            }
            "dir" => {
                let modified = if tokens.len() > 2 { parse_date(tokens[2]) } else { DateParts::default() };
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_entry(tokens[1], true, 0, modified));
            }
            "file" => {
                let size = parse_i64(tokens[2]);
                let modified = if tokens.len() > 3 { parse_date(tokens[3]) } else { DateParts::default() };
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_entry(tokens[1], false, size, modified));
            }
            "drive" => {
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_drive_entry(tokens[1], tokens[2], &unquote(tokens[3]), parse_i64(tokens[4]), parse_i64(tokens[5])));
            }
            "endlist" => current_list = None,
            "layout" => {
                layout.calculate(
                    width,
                    height,
                    matches!(tokens[1], "3pane" | "preview"),
                    matches!(tokens[1], "3pane" | "parent"),
                );
            }
            "headers" => {
                let flags: Vec<&str> = tokens[2..].to_vec();
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_column_headers(
                    buffer,
                    pane_rect(&layout, tokens[1]),
                    flags.contains(&"icons"),
                    flags.contains(&"size"),
                    flags.contains(&"date"),
                    flags.contains(&"drive"),
                    flags.contains(&"status"),
                );
            }
            "filelist" => {
                let pane = tokens[1];
                let list_name = tokens[2];
                let selected = parse_i32(tokens[3]);
                let scroll = parse_i32(tokens[4]);
                let active = tokens[5] == "active";
                let flags: Vec<&str> = tokens[6..].to_vec();
                let entries = &lists[list_name];
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_file_list(
                    buffer,
                    pane_rect(&layout, pane),
                    entries,
                    selected,
                    scroll,
                    active,
                    flags.contains(&"icons"),
                    flags.contains(&"size"),
                    flags.contains(&"date"),
                    &std::collections::HashSet::new(),
                    None,
                    None,
                    flags.contains(&"drive"),
                );
            }
            "message" => {
                let pane = tokens[1];
                let msg = unquote(line.splitn(3, ' ').nth(2).expect("message text"));
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_message(buffer, pane_rect(&layout, pane), &msg);
            }
            "notify" => {
                let msg = unquote(line.splitn(3, ' ').nth(2).expect("notification text"));
                notification = Some(Notification {
                    message: msg,
                    kind: match tokens[1] {
                        "success" => NotificationKind::Success,
                        "error" => NotificationKind::Error,
                        _ => NotificationKind::Info,
                    },
                    timestamp_ms: 0,
                });
            }
            "statusbar" => {
                // statusbar PATH SELECTED ITEM_COUNT [list LISTNAME]
                let path = unquote(tokens[1]);
                let selected = parse_i32(tokens[2]) as usize;
                let item_count = parse_i32(tokens[3]) as usize;
                let selected_entry = if tokens.len() > 5 && tokens[4] == "list" {
                    lists[tokens[5]].get(selected)
                } else {
                    None
                };
                let buffer = buffer.as_mut().expect("size op first");
                status_bar::render(
                    buffer,
                    layout.status_bar,
                    &path,
                    item_count,
                    selected,
                    selected_entry,
                    None,
                    None,
                    None,
                    notification.take(),
                    0,
                    SortMode::Name,
                    true,
                    0,
                    false,
                    None,
                    None,
                );
            }
            "help" => {
                let buffer = buffer.as_mut().expect("size op first");
                help_overlay::render(buffer, width, height);
            }
            "confirmdlg" => {
                // confirmdlg "TITLE" "MESSAGE"
                let title = unquote(tokens[1]);
                let message = unquote(line.splitn(3, ' ').nth(2).expect("message"));
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_confirm_dialog(
                    buffer,
                    width,
                    height,
                    if title == "-" { None } else { Some(&title) },
                    &message,
                );
            }
            "textinputdlg" => {
                // textinputdlg "TITLE" "VALUE"
                let title = unquote(tokens[1]);
                let value = unquote(line.splitn(3, ' ').nth(2).expect("value"));
                let mut input = TextInput::new(&value);
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_text_input_dialog(
                    buffer,
                    width,
                    height,
                    if title == "-" { None } else { Some(&title) },
                    Some(&mut input),
                );
            }
            "gotopathdlg" => {
                // gotopathdlg "VALUE" ["SUGGESTION"]
                let rest = line["gotopathdlg ".len()..].to_string();
                let spans = quoted_spans(&rest);
                let value = unquote(&spans[0]);
                let mut input = TextInput::new(&value);
                let suggestion = if spans.len() > 1 { Some(unquote(&spans[1])) } else { None };
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_go_to_path_dialog(buffer, width, height, Some(&mut input), suggestion.as_deref());
            }
            "palette" => {
                // palette "TITLE" DEPTH SELECTED
                let rest = &line["palette ".len()..];
                let spans = quoted_spans(rest);
                palette_title = spans[0].clone();
                let after_title = &rest[rest[1..].find('"').expect("closing quote") + 2..];
                let nums: Vec<&str> = after_title.split_whitespace().collect();
                palette_depth = parse_i32(nums[0]);
                palette_selected = parse_i32(nums[1]);
                palette_items = Some(Vec::new());
            }
            "pitem" => {
                // pitem "Label" "Shortcut" [sub]
                let spans = quoted_spans(&line["pitem ".len()..]);
                palette_items
                    .as_mut()
                    .expect("palette op first")
                    .push(ActionMenuItem::new(&spans[0], &spans[1], AppAction::None));
            }
            "endpalette" => {
                let items = palette_items.take().expect("palette op first");
                let mut level = ActionMenuLevel::new(&palette_title, items);
                level.selected_index = palette_selected.max(0) as usize;
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_action_palette(buffer, width, height, &mut level, palette_depth);
            }
            "searchbar" => {
                // searchbar ACTIVE "FILTER"
                let active = tokens[1] == "active";
                let filter = unquote(line.splitn(3, ' ').nth(2).expect("filter"));
                let mut input = TextInput::new(&filter);
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_search_bar(
                    buffer,
                    layout.center_pane,
                    active,
                    &filter,
                    if active { Some(&mut input) } else { None },
                );
            }
            "textinput" => {
                // textinput ROW COL WIDTH "VALUE"
                let row = parse_i32(tokens[1]);
                let col = parse_i32(tokens[2]);
                let w = parse_i32(tokens[3]);
                let value = unquote(line.splitn(5, ' ').nth(4).expect("value"));
                let mut input = TextInput::new(&value);
                let style = CellStyle {
                    fg: Some(Color { r: 200, g: 200, b: 200 }),
                    bg: None,
                    ..CellStyle::default()
                };
                let buffer = buffer.as_mut().expect("size op first");
                input.render(buffer, row, col, w, style);
            }
            "flush" => {
                let buffer = buffer.as_mut().expect("size op first");
                buffer.serialize(&mut out);
                flushes.push(out.clone());
            }
            "configdlg" => {
                config_state = Some(wade::ui::config_dialog::ConfigDialogState::from_app_config(&wade::app::AppConfig::default()));
            }
            "csel" => {
                config_state.as_mut().expect("configdlg op first").selected_index = parse_i32(tokens[1]).max(0) as usize;
            }
            "ctoggle" => {
                config_state.as_mut().expect("configdlg op first").toggle_selected();
            }
            "ccycle" => {
                let state = config_state.as_mut().expect("configdlg op first");
                if tokens[1] == "next" {
                    state.cycle_next_selected();
                } else {
                    state.cycle_prev_selected();
                }
            }
            "cnav" => {
                let state = config_state.as_mut().expect("configdlg op first");
                match tokens[1] {
                    "up" => state.move_up(),
                    "down" => state.move_down(),
                    "left" => state.cycle_prev_selected(),
                    _ => state.cycle_next_selected(),
                }
            }
            "configrender" => {
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_config_dialog(buffer, width, height, config_state.as_ref().expect("configdlg op first"));
            }
            "bmark" => {
                let store = bookmark_store.get_or_insert_with(|| {
                    wade::fs::bookmark_store::BookmarkStore::new(Some(
                        std::env::temp_dir().join(format!("wade-fixture-bookmarks-{}", std::process::id())),
                    ))
                });
                store.add(&unquote(line.split_once(' ').map(|x| x.1).expect("path")));
            }
            "bfilter" => {
                let mut input = TextInput::default();
                let value = unquote(line.split_once(' ').map(|x| x.1).expect("text"));
                for ch in value.chars() {
                    input.insert_char(ch);
                }
                bookmark_input = Some(input);
            }
            "bsel" => {
                bookmark_selected = parse_i32(tokens[1]).max(0) as usize;
            }
            "bscroll" => {
                bookmark_scroll = parse_i32(tokens[1]).max(0) as usize;
            }
            "bookmarkrender" => {
                let store = bookmark_store.as_ref().expect("bmark op first");
                let filter = bookmark_input.as_ref().map_or(String::new(), |input| input.value().to_string());
                let filtered: Vec<String> = store
                    .bookmarks()
                    .iter()
                    .filter(|bookmark| filter.is_empty() || bookmark.to_ascii_lowercase().contains(&filter.to_ascii_lowercase()))
                    .cloned()
                    .collect();
                let buffer = buffer.as_mut().expect("size op first");
                dialogs::render_bookmarks(buffer, width, height, &filtered, bookmark_selected, bookmark_scroll, bookmark_input.as_mut());
            }
            "ctxmenu" => {
                // ctxmenu ANCHORROW ANCHORCOL
                ctx_anchor = (parse_i32(tokens[1]), parse_i32(tokens[2]));
                ctx_items = Some(Vec::new());
            }
            "citem" => {
                let spans = quoted_spans(&line["citem ".len()..]);
                ctx_items
                    .as_mut()
                    .expect("ctxmenu op first")
                    .push(ActionMenuItem::new(&spans[0], &spans[1], AppAction::None));
            }
            "endctxmenu" => {
                let items = ctx_items.take().expect("ctxmenu op first");
                let state = wade::ui::context_menu::ContextMenuState::new(items, ctx_anchor.0, ctx_anchor.1);
                let buffer = buffer.as_mut().expect("size op first");
                wade::ui::context_menu::render(buffer, width, height, &state);
            }
            other => panic!("Unknown op '{other}' in {}", path.display()),
        }
    }

    assert!(buffer.is_some(), "scenario {} has no size op", path.display());

    let mut golden = String::new();
    for (i, flush) in flushes.iter().enumerate() {
        let _ = writeln!(golden, "=== flush {i} ===");
        let _ = writeln!(golden, "{flush}");
    }
    golden
}

const MIN_FIXTURES: usize = 5;

#[test]
fn renderer_fixtures_match_csharp_output() {
    let dir = golden_dir();
    let mut fixtures: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("golden dir")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "scn"))
        .collect();
    fixtures.sort();
    assert!(
        fixtures.len() >= MIN_FIXTURES,
        "no .scn fixtures found in {}",
        dir.display()
    );

    let mut compared = 0;
    for fixture_path in fixtures {
        let golden_path = fixture_path.with_extension("golden.txt");
        let expected = normalize_lf(&std::fs::read_to_string(&golden_path).unwrap_or_else(|_| {
            panic!(
                "missing golden file {}; generate with the C# test and WADE_UPDATE_GOLDENS=1",
                golden_path.display()
            )
        }));

        let actual = run_scenario(&fixture_path);
        if actual == "PLATFORM-SKIPPED" {
            continue;
        }

        assert_eq!(
            expected, actual,
            "golden mismatch for {}",
            fixture_path.display()
        );
        compared += 1;
    }

    assert!(
        compared >= MIN_FIXTURES,
        "expected at least {MIN_FIXTURES} fixtures, compared {compared}"
    );
}

// Suppress unused warnings for ported constants only reachable via fixtures.
#[test]
fn drives_path_constant_matches_csharp() {
    assert_eq!(DRIVES_PATH, "::drives");
}
