//! Renderer golden-frame parity tests: executes the shared fixture files
//! from tests/golden/renderer/ and compares against the golden files
//! generated by tests/Wade.Tests/PaneRendererGoldenTests.cs.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use wade::fs::directory_contents::{FileSystemEntry, SortMode, DRIVES_PATH};
use wade::screen::ScreenBuffer;
use wade::ui::format_helpers::DateParts;
use wade::ui::layout::{Layout, Rect};
use wade::ui::notification::{Notification, NotificationKind};
use wade::ui::pane_renderer::PaneRenderer;
use wade::ui::status_bar;

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/renderer")
}

fn parse_i32(token: &str) -> i32 {
    token.parse().expect("integer token")
}

fn parse_i64(token: &str) -> i64 {
    token.parse().expect("long token")
}

fn parse_date(token: &str) -> DateParts {
    // yyyy-MM-ddTHH:mm:ss
    let bytes = token.as_bytes();
    assert_eq!(token.len(), 19, "date format: {token}");
    let num = |a: usize, b: usize| -> i32 {
        token[a..b].parse().expect("date component")
    };
    let _ = bytes;
    assert_eq!(&token[4..5], "-");
    assert_eq!(&token[7..8], "-");
    assert_eq!(&token[10..11], "T");
    assert_eq!(&token[13..14], ":");
    assert_eq!(&token[16..17], ":");
    DateParts {
        year: num(0, 4),
        month: num(5, 7) as u32,
        day: num(8, 10) as u32,
        hour: num(11, 13) as u32,
        minute: num(14, 16) as u32,
    }
}

fn unquote(s: &str) -> String {
    s.trim_matches('"').to_string()
}

fn make_entry(name: &str, is_directory: bool, size: i64, modified: DateParts) -> FileSystemEntry {
    FileSystemEntry {
        name: name.to_string(),
        full_path: format!("C:/fixture/{name}"),
        is_directory,
        size,
        last_modified: modified,
        link_target: None,
        is_broken_symlink: false,
        is_drive: false,
        is_cloud_placeholder: false,
        is_junction_point: false,
        is_app_exec_link: false,
        app_exec_link_target: None,
        drive_format: None,
        drive_label: None,
        drive_free_space: 0,
        drive_total_size: 0,
    }
}

fn make_drive_entry(name: &str, format: &str, label: &str, free: i64, total: i64) -> FileSystemEntry {
    FileSystemEntry {
        name: name.to_string(),
        full_path: format!("{name}\\"),
        is_directory: true,
        size: 0,
        last_modified: DateParts::default(),
        link_target: None,
        is_broken_symlink: false,
        is_drive: true,
        is_cloud_placeholder: false,
        is_junction_point: false,
        is_app_exec_link: false,
        app_exec_link_target: None,
        drive_format: Some(format.to_string()),
        drive_label: Some(label.to_string()),
        drive_free_space: free,
        drive_total_size: total,
    }
}

fn pane_rect(layout: &Layout, pane: &str) -> Rect {
    match pane {
        "left" => layout.left_pane,
        "right" => layout.right_pane,
        _ => layout.center_pane,
    }
}

fn run_scenario(path: &Path) -> String {
    let text = std::fs::read_to_string(path).expect("read fixture");
    let mut width = 80;
    let mut height = 25;
    let mut buffer: Option<ScreenBuffer> = None;
    let mut layout = Layout::default();
    let mut lists: HashMap<String, Vec<FileSystemEntry>> = HashMap::new();
    let mut current_list: Option<String> = None;
    let mut notification: Option<Notification> = None;
    let mut flushes: Vec<String> = Vec::new();
    let mut out = String::new();

    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let tokens: Vec<&str> = line.split_whitespace().collect();
        match tokens[0] {
            "size" => {
                width = parse_i32(tokens[1]);
                height = parse_i32(tokens[2]);
                buffer = Some(ScreenBuffer::new(width, height));
            }
            "list" => {
                lists.insert(tokens[1].to_string(), Vec::new());
                current_list = Some(tokens[1].to_string());
            }
            "dir" => {
                let modified = if tokens.len() > 2 { parse_date(tokens[2]) } else { DateParts::default() };
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_entry(tokens[1], true, 0, modified));
            }
            "file" => {
                let size = parse_i64(tokens[2]);
                let modified = if tokens.len() > 3 { parse_date(tokens[3]) } else { DateParts::default() };
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_entry(tokens[1], false, size, modified));
            }
            "drive" => {
                lists.get_mut(current_list.as_ref().expect("list op first"))
                    .expect("current list")
                    .push(make_drive_entry(tokens[1], tokens[2], &unquote(tokens[3]), parse_i64(tokens[4]), parse_i64(tokens[5])));
            }
            "endlist" => current_list = None,
            "layout" => {
                layout.calculate(
                    width,
                    height,
                    matches!(tokens[1], "3pane" | "preview"),
                    matches!(tokens[1], "3pane" | "parent"),
                );
            }
            "headers" => {
                let flags: Vec<&str> = tokens[2..].to_vec();
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_column_headers(
                    buffer,
                    pane_rect(&layout, tokens[1]),
                    flags.contains(&"icons"),
                    flags.contains(&"size"),
                    flags.contains(&"date"),
                    flags.contains(&"drive"),
                    flags.contains(&"status"),
                );
            }
            "filelist" => {
                let pane = tokens[1];
                let list_name = tokens[2];
                let selected = parse_i32(tokens[3]);
                let scroll = parse_i32(tokens[4]);
                let active = tokens[5] == "active";
                let flags: Vec<&str> = tokens[6..].to_vec();
                let entries = &lists[list_name];
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_file_list(
                    buffer,
                    pane_rect(&layout, pane),
                    entries,
                    selected,
                    scroll,
                    active,
                    flags.contains(&"icons"),
                    flags.contains(&"size"),
                    flags.contains(&"date"),
                    &std::collections::HashSet::new(),
                    None,
                    None,
                    flags.contains(&"drive"),
                );
            }
            "message" => {
                let pane = tokens[1];
                let msg = unquote(line.splitn(3, ' ').nth(2).expect("message text"));
                let buffer = buffer.as_mut().expect("size op first");
                PaneRenderer::render_message(buffer, pane_rect(&layout, pane), &msg);
            }
            "notify" => {
                let msg = unquote(line.splitn(3, ' ').nth(2).expect("notification text"));
                notification = Some(Notification {
                    message: msg,
                    kind: match tokens[1] {
                        "success" => NotificationKind::Success,
                        "error" => NotificationKind::Error,
                        _ => NotificationKind::Info,
                    },
                    timestamp_ms: 0,
                });
            }
            "statusbar" => {
                // statusbar PATH SELECTED ITEM_COUNT [list LISTNAME]
                let path = unquote(tokens[1]);
                let selected = parse_i32(tokens[2]) as usize;
                let item_count = parse_i32(tokens[3]) as usize;
                let selected_entry = if tokens.len() > 5 && tokens[4] == "list" {
                    lists[tokens[5]].get(selected)
                } else {
                    None
                };
                let buffer = buffer.as_mut().expect("size op first");
                status_bar::render(
                    buffer,
                    layout.status_bar,
                    &path,
                    item_count,
                    selected,
                    selected_entry,
                    None,
                    None,
                    None,
                    notification.take(),
                    0,
                    SortMode::Name,
                    true,
                    0,
                    false,
                    None,
                    None,
                );
            }
            "flush" => {
                let buffer = buffer.as_mut().expect("size op first");
                buffer.serialize(&mut out);
                flushes.push(out.clone());
            }
            other => panic!("Unknown op '{other}' in {}", path.display()),
        }
    }

    assert!(buffer.is_some(), "scenario {} has no size op", path.display());

    let mut golden = String::new();
    for (i, flush) in flushes.iter().enumerate() {
        let _ = writeln!(golden, "=== flush {i} ===");
        let _ = writeln!(golden, "{flush}");
    }
    golden
}

const MIN_FIXTURES: usize = 5;

#[test]
fn renderer_fixtures_match_csharp_output() {
    let dir = golden_dir();
    let mut fixtures: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("golden dir")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "scn"))
        .collect();
    fixtures.sort();
    assert!(
        fixtures.len() >= MIN_FIXTURES,
        "no .scn fixtures found in {}",
        dir.display()
    );

    let mut compared = 0;
    for fixture_path in fixtures {
        let golden_path = fixture_path.with_extension("golden.txt");
        let expected = std::fs::read_to_string(&golden_path).unwrap_or_else(|_| {
            panic!(
                "missing golden file {}; generate with the C# test and WADE_UPDATE_GOLDENS=1",
                golden_path.display()
            )
        });

        let actual = run_scenario(&fixture_path);
        assert_eq!(
            expected, actual,
            "golden mismatch for {}",
            fixture_path.display()
        );
        compared += 1;
    }

    assert!(
        compared >= MIN_FIXTURES,
        "expected at least {MIN_FIXTURES} fixtures, compared {compared}"
    );
}

// Suppress unused warnings for ported constants only reachable via fixtures.
#[test]
fn drives_path_constant_matches_csharp() {
    assert_eq!(DRIVES_PATH, "::drives");
}
